# Generated by Django 5.2.8 on 2025-11-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the TODO title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description', null=True)),
                ('due_date', models.DateField(blank=True, help_text='Optional due date', null=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Mark as complete')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Priority level', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TODO',
                'verbose_name_plural': 'TODOs',
                'ordering': ['is_resolved', '-priority', 'due_date', '-created_at'],
            },
        ),
    ]
